### ISSUE TITLE
Enhancement: allow to override functions: eval, print, echo...

### ISSUE THREAD

**Issue by scratcher28** [dmtrkzntsv/php-runtime#2]
Hi.

Is it possible to implement overriding of functions: eval, print, echo (...) ?

**Comment by dmtrkzntsv** [comment]
Hi,
I think, that it is possible.
But I have some troubles, because "print", "echo" this is language construct, not a function.
Tomorrow, I'll try make this feature

**Comment by scratcher28** [comment]
Any success? ;)

**Comment by dmtrkzntsv** [comment]
Sorry for very long waiting.
I tried to implement print, echo, exit, die. But as I wrote - this is a language constructs, not a functions.
If you use this as 

``` php
echo('aaa');
exit();
print(123);
```

my patch will work, but if you use this as 

``` php
echo '123';
```

will be with error.

Eval can disable and overwriting normally.

**Comment by scratcher28** [comment]
Ok, got it. Thanks.
